In [3]:
import numpy as np

In [ ]:
one_d_array = np.array([1, 2, 3]) #One dimensional array
print(one_d_array)

[1 2 3]


In [28]:
one_d_array.size

3

In [33]:
one_d_array.shape  

(3,)

In [37]:
one_d_array.dtype

dtype('int32')

In [39]:
one_d_array.astype('float64')

array([1., 2., 3.])

In [65]:
np.append(one_d_array , 4)

array([1, 2, 3, 4])

In [69]:
np.insert(one_d_array , 1 , 1.5)

array([1, 1, 2, 3])

In [70]:
np.delete(one_d_array , 2)

array([1, 2])

In [48]:
np.info(np.eye)   # View documentation for np.eye

 eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)

Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    com

In [ ]:
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])   #  Two dimensional array
print(two_d_array)

[[1 2 3]
 [4 5 6]]


In [29]:
two_d_array.size

6

In [34]:
two_d_array.shape

(2, 3)

In [44]:
two_d_array.tolist()

[[1, 2, 3], [4, 5, 6]]

In [68]:
np.append(two_d_array , [2] , )

array([1, 2, 3, 4, 5, 6, 2])

In [ ]:
one_d_zero = np.zeros(3)   #   1D array of length 3 all values 0
print(one_d_zero)

[0. 0. 0.]


In [22]:
multi_d = np.zeros((2, 3)) # 2x3 array of zeros
print(multi_d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [23]:
one_value = np.ones((3,4))  #   3x4 array with all values 1
print(one_value)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
unit_array = np.eye(5)    # 5x5 array of 0 with 1 on diagonal
print(unit_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [30]:
unit_array.size

25

In [35]:
unit_array.shape

(5, 5)

In [38]:
unit_array.dtype

dtype('float64')

In [45]:
unit_array.tolist()

[[1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 1.0]]

In [43]:
unit_array.astype(bool)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

In [ ]:
a = np.linspace(0,100,7)  #  Array of 6 evenly divided values from 0 to 100
print(a)

[  0.          16.66666667  33.33333333  50.          66.66666667
  83.33333333 100.        ]


In [40]:
a.astype('int32')

array([  0,  16,  33,  50,  66,  83, 100])

In [ ]:
b = np.arange(0,10,3)   #  Array of values from 0 to less than 10 with step 3
print(b)

[0 3 6 9]


In [24]:
np.full((2,3),8)   #  2x3 array with all values 8

array([[8, 8, 8],
       [8, 8, 8]])

In [25]:
np.random.rand(4,5)   #  4x5 array of random values between 0 and 1

array([[0.45157749, 0.94213961, 0.34129802, 0.76552648, 0.88410234],
       [0.67214815, 0.41895584, 0.65227059, 0.94291766, 0.02876872],
       [0.94457709, 0.03173158, 0.70712766, 0.95426982, 0.77422609],
       [0.03715312, 0.9228704 , 0.48977007, 0.50361569, 0.00922347]])

In [41]:
rand_arr = np.random.rand(6,7)*100   #  6x7 array of random values between 0 and 100
print(rand_arr)

[[56.89009122 92.69732233 93.3640473  12.54019526  5.73517434 78.14397073
  83.51693826]
 [76.2607735  81.03520738 90.08015306 12.62051526 65.46775523 23.45484871
  56.9556384 ]
 [28.58372047 20.8419383  28.81563741 12.05262833 80.25498927  1.30645817
  39.2299692 ]
 [37.28269904 46.62254748  0.96194631 88.73393796 73.10901571 84.16435045
  15.6502112 ]
 [95.76564458 88.79117963 58.0031241   2.70498644 80.37338802 97.90220537
  86.92368389]
 [50.4859649  12.56651559 82.29045673 72.68956143 69.7031323  83.40259239
  21.22051664]]


In [32]:
rand_arr.size

42

In [36]:
rand_arr.shape

(6, 7)

In [53]:
rand_arr.sort()
print(rand_arr)

[[ 5.73517434 12.54019526 56.89009122 78.14397073 83.51693826 92.69732233
  93.3640473 ]
 [12.62051526 23.45484871 56.9556384  65.46775523 76.2607735  81.03520738
  90.08015306]
 [ 1.30645817 12.05262833 20.8419383  28.58372047 28.81563741 39.2299692
  80.25498927]
 [ 0.96194631 15.6502112  37.28269904 46.62254748 73.10901571 84.16435045
  88.73393796]
 [ 2.70498644 58.0031241  80.37338802 86.92368389 88.79117963 95.76564458
  97.90220537]
 [12.56651559 21.22051664 50.4859649  69.7031323  72.68956143 82.29045673
  83.40259239]]


In [55]:
rand_arr.sort(axis=0)
print(rand_arr)

[[ 0.96194631 12.05262833 20.8419383  28.58372047 28.81563741 39.2299692
  80.25498927]
 [ 1.30645817 12.54019526 37.28269904 46.62254748 72.68956143 81.03520738
  83.40259239]
 [ 2.70498644 15.6502112  50.4859649  65.46775523 73.10901571 82.29045673
  88.73393796]
 [ 5.73517434 21.22051664 56.89009122 69.7031323  76.2607735  84.16435045
  90.08015306]
 [12.56651559 23.45484871 56.9556384  78.14397073 83.51693826 92.69732233
  93.3640473 ]
 [12.62051526 58.0031241  80.37338802 86.92368389 88.79117963 95.76564458
  97.90220537]]


In [42]:
rand_arr.astype(bool)

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [27]:
np.random.randint(5,size=(2,3))   #  2x3 array of random integers between 0 and 5

array([[1, 4, 3],
       [0, 4, 2]])

In [56]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [57]:
arr.flatten()   

array([1, 2, 3, 4, 5, 6])

In [61]:
arr1 = np.array([[1, 2, 3 , 7], [4, 5, 6 , 8]])
print(arr1)

[[1 2 3 7]
 [4 5 6 8]]


In [62]:
arr1.T

array([[1, 4],
       [2, 5],
       [3, 6],
       [7, 8]])

In [64]:
arr1.reshape(2,4)

array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

In [71]:
first_array = ([1,2,3,4,5])
second_array = ([6,7,8,9,10])

In [78]:
mixed_arr = np.concatenate((first_array , second_array) , axis = 0)   #  Concatenate two 1D arrays
print(mixed_arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [74]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr3 = np.array([[7, 8, 9], [10, 11, 12]])

In [82]:
two_d_mix = np.concatenate((arr2 , arr3) , axis = 1)
print(two_d_mix)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [80]:
np.split(mixed_arr , 5)   # Split 1D array into 3 sub-arrays

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]

In [88]:
np.split(two_d_mix , 3 , axis = 1)   # Split 2D array into 3 sub-arrays along columns

[array([[1, 2],
        [4, 5]]),
 array([[ 3,  7],
        [ 6, 10]]),
 array([[ 8,  9],
        [11, 12]])]

In [86]:
np.hsplit(two_d_mix , 3)   # Split 2D array into 3 sub-arrays along columns

[array([[1, 2],
        [4, 5]]),
 array([[ 3,  7],
        [ 6, 10]]),
 array([[ 8,  9],
        [11, 12]])]

In [92]:
ex_arr = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(ex_arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [93]:
ex_arr[5]

5

In [96]:
ex_arr[3] = 4
print(ex_arr)

[ 0  1  2  4  4  5  6  7  8  9 10]


In [98]:
ex_arr[0:3]

array([0, 1, 2])

In [105]:
ex_arr < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False])

In [108]:
~ex_arr

array([ -1,  -2,  -3,  -5,  -5,  -6,  -7,  -8,  -9, -10, -11])

In [109]:
np.add(ex_arr , 5)

array([ 5,  6,  7,  9,  9, 10, 11, 12, 13, 14, 15])

In [110]:
np.subtract(ex_arr , 3)

array([-3, -2, -1,  1,  1,  2,  3,  4,  5,  6,  7])

In [112]:
np.multiply(ex_arr , 4)

array([ 0,  4,  8, 16, 16, 20, 24, 28, 32, 36, 40])

In [113]:
np.divide(ex_arr , 2)

array([0. , 0.5, 1. , 2. , 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [114]:
np.power(ex_arr , 2)

array([  0,   1,   4,  16,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [116]:
arr_1 = np.array([1,2,3,4,5])
arr_2 = np.array([6,7,8,9,10])

In [117]:
np.add(arr_1 , arr_2)

array([ 7,  9, 11, 13, 15])

In [118]:
np.subtract(arr_1 , arr_2)

array([-5, -5, -5, -5, -5])

In [119]:
np.multiply(arr_1 , arr_2)

array([ 6, 14, 24, 36, 50])

In [120]:
np.divide(arr_2 , arr_1)

array([6.        , 3.5       , 2.66666667, 2.25      , 2.        ])

In [121]:
np.array_equal(arr_1 , arr_2)

False

In [125]:
one_more_array = np.array([0 , 4 , 9 , 16 , 25 , 26])

In [126]:
np.sqrt(one_more_array)

array([0.        , 2.        , 3.        , 4.        , 5.        ,
       5.09901951])

In [127]:
np.sin(one_more_array)

array([ 0.        , -0.7568025 ,  0.41211849, -0.28790332, -0.13235175,
        0.76255845])

In [128]:
np.log(one_more_array)

C:\Users\shaba\AppData\Local\Temp\ipykernel_15172\816036828.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(one_more_array)


array([      -inf, 1.38629436, 2.19722458, 2.77258872, 3.21887582,
       3.25809654])

In [129]:
np.abs(one_more_array)

array([ 0,  4,  9, 16, 25, 26])

In [130]:
np.ceil(one_more_array)

array([ 0.,  4.,  9., 16., 25., 26.])

In [131]:
np.floor(one_more_array)

array([ 0.,  4.,  9., 16., 25., 26.])

In [132]:
simple_array = np.array([-2.5 , 1.5 , -0.5 , 4.5 , 3.5])

In [133]:
np.mean(simple_array)

1.3

In [134]:
simple_array.sum()

6.5

In [135]:
simple_array.min()

-2.5

In [136]:
np.var(simple_array)

6.5600000000000005

In [137]:
np.std(simple_array)

2.5612496949731396

In [138]:
np.abs(simple_array)

array([2.5, 1.5, 0.5, 4.5, 3.5])

In [139]:
np.ceil(simple_array)

array([-2.,  2., -0.,  5.,  4.])

In [140]:
np.floor(simple_array)

array([-3.,  1., -1.,  4.,  3.])

In [141]:
np.round(simple_array)

array([-2.,  2., -0.,  4.,  4.])