In [1]:
from sklearn.model_selection import train_test_split
import numpy as np

X = np.random.rand(100, 5)
y = np.random.randint(0, 2, size=100)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(X_train.shape, X_test.shape)

(80, 5) (20, 5)


In [2]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(X_train_scaled[:5])

[[ 0.52424521 -1.4239139   1.19087513  0.65491629 -1.57384964]
 [-0.31753339  1.11483721 -1.27277999  1.64485026 -1.17320839]
 [ 1.08439164  0.60013645  0.9345456  -0.56912949  1.07845555]
 [-0.90517671 -0.33681949  1.50253667  0.49129814  0.04942324]
 [ 0.50511664 -0.50655016 -1.7777257  -0.77028739  0.84082427]]


In [3]:
from sklearn.preprocessing import Normalizer

scaler = Normalizer().fit(X_train)
X_train_norm = scaler.transform(X_train)
print(X_train_norm[:5])

[[0.54112269 0.10085125 0.66338942 0.50664912 0.01537511]
 [0.35880875 0.61230461 0.10845022 0.68921063 0.09780903]
 [0.53252889 0.43914024 0.49722618 0.19196989 0.48936952]
 [0.25527274 0.32196514 0.70586581 0.45290775 0.35749447]
 [0.63782969 0.3534628  0.00224781 0.22463515 0.64635233]]


In [4]:
from sklearn.preprocessing import LabelEncoder

y_encoded = LabelEncoder().fit_transform(y)
print(y_encoded[:10])

[0 0 0 0 0 1 0 1 0 1]


In [5]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
print(y_pred[:5])

[0.33037267 0.52332985 0.40154842 0.53805908 0.36442609]


In [6]:
from sklearn.svm import SVC

svc = SVC(kernel='linear')
svc.fit(X_train, y_train)
y_pred = svc.predict(X_test)
print(y_pred[:10])

[0 0 0 0 0 0 0 0 0 0]


In [7]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)
print(y_pred[:10])

[0 1 0 1 0 0 0 0 0 0]


In [8]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print(y_pred[:10])

[0 0 1 0 0 0 0 1 0 0]


In [9]:
from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.5


In [10]:
from sklearn.metrics import confusion_matrix

print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Confusion Matrix:
 [[9 3]
 [7 1]]


In [11]:
from sklearn.metrics import classification_report

print("Classification Report:\n", classification_report(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

           0       0.56      0.75      0.64        12
           1       0.25      0.12      0.17         8

    accuracy                           0.50        20
   macro avg       0.41      0.44      0.40        20
weighted avg       0.44      0.50      0.45        20



In [12]:
from sklearn.metrics import mean_squared_error

print("MSE:", mean_squared_error(y_test, y_pred))

MSE: 0.5


In [13]:
from sklearn.metrics import r2_score

print("R²:", r2_score(y_test, y_pred))

R²: -1.083333333333333


In [14]:
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
scores = cross_val_score(knn, X, y, cv=5)
print("Cross-val scores:", scores)
print("Mean:", scores.mean())

Cross-val scores: [0.6 0.3 0.4 0.5 0.4]
Mean: 0.43999999999999995
