In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])   # 1D array
print(a)

[1 2 3]


In [3]:
b = np.array([(1, 2, 3), (4, 5, 6)])   # 2D array
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
np.zeros((3, 4))   # 3x4 zero array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones((2, 3))    # 2x3 ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.eye(4)   # Identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
np.linspace(0, 10, 5)   # 5 evenly spaced numbers from 0 to 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [8]:
np.arange(0, 10, 2)   # Values from 0 to <10 step 2

array([0, 2, 4, 6, 8])

In [9]:
np.random.rand(3, 3)   # Random floats 0–1

array([[0.14550756, 0.64569318, 0.20881324],
       [0.13792319, 0.01652877, 0.36702523],
       [0.01816528, 0.53177032, 0.48314841]])

In [10]:
np.random.randint(5, size=(2, 3))   # Random ints 0–4

array([[1, 1, 2],
       [3, 4, 1]])

In [11]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.size)     # Number of elements
print(arr.shape)    # Dimensions
print(arr.dtype)    # Data type

6
(2, 3)
int32


In [12]:
arr = np.array([3,1,2])
print(np.copy(arr))

[3 1 2]


In [13]:
arr.sort()
print(arr)

[1 2 3]


In [14]:
mat = np.array([[1,2,3],[4,5,6]])
print(mat.T)   # Transpose

[[1 4]
 [2 5]
 [3 6]]


In [15]:
arr = np.arange(12).reshape(3,4)   # Reshape
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [16]:
arr = np.array([1,2,3])
print(np.append(arr, [4,5]))

[1 2 3 4 5]


In [17]:
arr = np.array([1,2,3,4])
print(np.delete(arr, 2))

[1 2 4]


In [18]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.concatenate((a,b)))

[1 2 3 4 5 6]


In [19]:
arr = np.arange(9)
print(np.split(arr, 3))

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [20]:
arr = np.arange(10)
print(arr[5])       # Element
print(arr[2:7])     # Slice

5
[2 3 4 5 6]


In [21]:
mat = np.arange(12).reshape(3,4)
print(mat[1,2])     # 2nd row, 3rd col
print(mat[:,1])     # All rows, col 2

6
[1 5 9]


In [22]:
arr = np.array([1,2,3])
print(np.add(arr, 1))
print(np.power(arr, 2))

[2 3 4]
[1 4 9]


In [23]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.add(a, b))
print(np.multiply(a, b))
print(np.sqrt(b))

[5 7 9]
[ 4 10 18]
[2.         2.23606798 2.44948974]


In [24]:
arr = np.array([1,2,3,4,5])
print(np.mean(arr))
print(arr.sum())
print(arr.min())
print(arr.max())
print(np.var(arr))
print(np.std(arr))

3.0
15
1
5
2.0
1.4142135623730951
